---
- name: install nginx
  hosts: "{{hosts}}"
  become: true
  
  tasks:
    - name: Put SELinux in permissive mode
      selinux:
        policy: targeted
        state: permissive

- name: install nginx
  hosts: "{{hosts}}"
  
  tasks:
  - name: install epel
    yum:
      name: epel-release
      state: present

  - name: install nginx
    yum:
      name: nginx
      state: present

- name: download moodle
  hosts: "{{hosts}}"
  
  tasks:
    - name: Creat path www/html
      file:
        path: /var/www/html/
        owner: nginx
        group: nginx
        mode: u+rwx,g-rw,o-r
        state: directory

    - name: find url for moodle
      unarchive:
        src: https://download.moodle.org/stable37/moodle-latest-37.tgz
        dest: /var/www/html/
        owner: nginx
        group: nginx
        mode: '0755'
        remote_src: true

- name: configuer nginx to start moodle
  hosts: "{{hosts}}"

  tasks:
    - name: creat moodle.conf
      file:
        path: /etc/nginx/conf.d/moodle.conf
        state: touch

    - name: insert tamplet in moodle.conf
      template:
        src: file.j2
        dest: /etc/nginx/conf.d/moodle.conf

- name: create moodledata
  hosts: "{{hosts}}"

  tasks:
    - name: creat modledata
      file:
        path: /var/www/html/
        owner: nginx
        group: nginx
        mode: '0777'

- name:  Configure firewalled
  hosts: "{{hosts}}"

  tasks:
    - name: enable port 80
      firewalld:
        port: 80/tcp
        state: enabled
        immediate: true
        permanent: true

- name: restart nginx
  hosts: "{{hosts}}"

  tasks:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
        enabled: true

